apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mydaemon
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
       - name: nginxcontainer
         image: nginx
         ports:
           - containerPort: 80
