apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc2
spec:
  replicas: 3
  selector:
    app: fb
  template:
    metadata:
      labels:
        app: fb
    spec:
      containers:
        - name: nginxcontainer
          image: nginx
          ports:
            - containerPort: 80
