apiVersion: batch/v1
kind: CronJob
metadata:
  name: minute-backup
  namespace: nginx

spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: minute-backup
          labels:
            app: minute-backup

        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup-container
              image: busybox
              command:
                - sh
                - -c
                - >
                  echo "backup started" &&
                  mkdir -p /backup &&
                  mkdir -p /data &&
                  cp -r /demo-data /backup &&
                  echo "backup completed";
              volumeMounts:
                - name: data-volume
                  mountPath: /demo-data
                - name: backup-volume
                  mountPath: /backup
          volumes:
            - name: data-volume
              hostPath:
                path: /demo-data
                type: DirectoryOrCreate
            - name: backup-volume
              hostPath:
                path: /backup
                type: DirectoryOrCreate
